### ISSUE TITLE
phpBB 3.3.12

### ISSUE THREAD

**Issue by dbrewood** [Tatiana5/QuickReply#101]
According to this post https://www.phpbb.com/community/viewtopic.php?p=16017604#p16017604 the extension breaks phpBB 3.3.12. Is there any chance it can be made compatible?
Thanks in advance.

**Comment by Tatiana5** [comment]
No, it work

**Comment by dbrewood** [comment]
My users (and myself) are reporting Java errors when we look to save a post. This is using the latest beta.

**Comment by Tatiana5** [comment]
2.1.1-beta?

**Comment by dbrewood** [comment]
Yes...... is that the version we should be using?

**Comment by Tatiana5** [comment]
Yes, this one. And there is definitely no error from the topic in it

**Comment by dbrewood** [comment]
Okay I'll look to see if I can do another clean install of it and we'll see how it goes. That will likely be after we get back from holiday though. I'll report back as soon as I can. Thanks.
