### ISSUE TITLE
Quick Reply zone not present/working in phpBB 3.1.1

### ISSUE THREAD

**Issue by cazzoo** [Tatiana5/QuickReply#17]
I just installed phpBB-3.1.1 Release and your extension to my board but it's not working as expected.
The QuickReply zone is not present at the bottom of the forum thread and all the features about highlighting text to quick reply is not present.
No error is thrown in browser JS profiler nor in phpBB logs.
The extension is well installed and activated, also all the params are set to enable it for the board.

**Comment by SamaelDark** [comment]
Форум на phpbb 3.1.3.
"Быстрая цитата" и "обратиться по нику" при наведении на ник в минипрофиле срабатывают только в первом сообщении на странице. В остальных его как будто нет.
Стандартный "быстрый ответ" включён на всех форумах без исключения.
Помимо Quick Reply установлены следующие моды:
Advanced BBCode Box 3.1.0
Auto Database Backup 1.1.0
Ban Hammer 1.0.0
Board Rules 1.0.1
Collapse Categories Light 1.0.2
Delete unnecessary notifications 0.0.1
Empennage: add code and content to the top/bottom of pages 0.1.3
External Links Open in New Window 1.0.0
FAQ manager 1.0.0
Favicon 0.0.2
Individual posts per page 1.0.0
Inline images in attachment 1.0.0
List subforums in columns 2.0.0
OneAll Social Login 2.4.2
Pages 1.0.2
phpBB3 SEO Sitemap 1.0.3
PostSubject 0.0.4
Private Message Box Status Bars 2.0.0
Profile side switcher 0.0.1
Rank Post Styling 1.0.3
Reputation System 1.0.0-dev
s9e/mediaembed 20150104
Scroll To Top 1.0.0
SEO Topic & Canonical URL 1.0.3
Team Avatar 1.0.0
Top Five 1.0.0
Topic Preview 2.2.1
User Merge 1.0.0
User topics & posts per page 1.0.0

Версия Quick Reply 0.1.4-dev.
