### ISSUE TITLE
BBCode marq up the windows view with Google Chrome

### ISSUE THREAD

**Issue by Galixte** [Tatiana5/QuickReply#26]
Hi,

please see that: https://github.com/VSEphpbb/abbc3/issues/15

**Comment by Galixte** [comment]
Hi @Tatiana5,

could you take a look ?

**Comment by lavigor** [comment]
I don't think that this is a problem of QuickReply extension anymore.
Also the HTML element `<marquee>` isn't valid and should be replaced with CSS animation.
The issue is closed because of these reasons.
