### ISSUE TITLE
Quickedit extension compatibility

### ISSUE THREAD

**Issue by Galixte** [Tatiana5/QuickReply#33]
Hi @lavigor @marc1706,

if i post a message with QuickReply Reloaded i can’t use the edit button with the Quickedit extension functionality: https://github.com/marc1706/phpbb3-ext-quickedit.

Maybe Marc has to read this: https://github.com/Tatiana5/QuickReply/wiki#how-to-make-this-extension-compatible-with-other-extensions & https://github.com/Tatiana5/QuickReply/wiki#developers-guide.

Or maybe it's a bug in QuickReply Reloaded extension.

**Comment by lavigor** [comment]
The JavaScript event `qr_completed` should be used in that extension for adding its functionality.

**Comment by Galixte** [comment]
Ok, thanks i hope that @marc will see your post.

**Comment by Galixte** [comment]
Thanks @lavigor !

Fully functional for me, fixed here: https://github.com/marc1706/phpbb3-ext-quickedit/pull/72.
