### ISSUE TITLE
Posts merging extension compatibility

### ISSUE THREAD

**Issue by Galixte** [Tatiana5/QuickReply#36]
Hi @lavigor,

from this commit: https://github.com/Tatiana5/QuickReply/commit/4b9db88e91bbe76abb004addc72ada905c6569a7#diff-5b16f81e26748b1551589589de97e98a, the compatibility with the Posts merging extension was added.

But if i disable the setting option: 
```
Posts merging interval:
If a user submit more than 2 posts in this time period, posts will be merged into one post. Information about the time passed from the previous post submitting will be added (for each post). Leave blank or set 0 to disable posts merging.
```
The button: “Do not merge with previous post” is still displayed under the text area, in the Quick reply.
While on the posting.php page (Post a reply page) this option is hidden correctly.

**Comment by lavigor** [comment]
The button “Do not merge with previous post” is always displayed if PostsMerging extension is installed.
However, I can write the fix for this case. =)

**Comment by Galixte** [comment]
Thanks !
