### ISSUE TITLE
quote button disappears from messages

### ISSUE THREAD

**Issue by papermate** [Tatiana5/QuickReply#77]
Hello everyone,
ext version: quick reply reloaded v. 2.0.0 beta (just downloaded from the website really)
phpbb: 3.2.1

Problem:
when quick reply reloaded is enabled the quote button disappears from the messages, it reappears if the extension is disabled. 

I would give it a high priority, as it is so uncomfortable like this that I am not using the extension.

Thanks for the work!

**Comment by lavigor** [comment]
Hello, @papermate,
What style do you use on your board?
Does this problem occur in prosilver?

**Comment by papermate** [comment]
hello @lavigor ,
I use a custom style but yes, this problem occours also on an untouched prosilver (both the latest version and the one from 3.2)

Thanks

**Comment by Tatiana5** [comment]
It is not a problem, it is the future. In the QuickReply ext a lot of settings and permissions for quote, customize the extension

**Comment by papermate** [comment]
hello @Tatiana5, sorry but I haven't understood your answer. What do you mean it's the future and not a problem? And what does the second phrase mean? Do you mean that there will be an option in the ACP to hide the quote button?

Sorry, I'm not a native English.

**Comment by Tatiana5** [comment]
I am not a native English too.

Screenshots
<img src="http://storage1.static.itmages.ru/i/17/0904/h_1504550884_8310291_9a5728c21e.jpeg" />

<img src="http://storage4.static.itmages.ru/i/17/0904/h_1504550907_8394211_0f3a683e8e.jpeg" />

**Comment by papermate** [comment]
Hi, thanks for your answer. I found the problem, for some reason every time I select all yes to the QuickQuote settings and I save, the option reverts back to "No" for the Insert quick quote using button. That is weird, I don't know if it's just me. I'll let you know if I find out anything.

Have a nice day

**Comment by Tatiana5** [comment]
@papermate 
1. Remove QuickReply completely
2. Reinstall it

The problem will be fixed
