### ISSUE TITLE
Version 1.1.0-RC2

### ISSUE THREAD

**Issue by ricardorohde** [Tatiana5/QuickReply#78]
[phpBB Debug] PHP Warning: in file [ROOT]/phpbb/class_loader.php on line 160: require(./../ext/boardtools/quickreply/event/listener_helper.php): failed to open stream: No such file or directory
[phpBB Debug] PHP Warning: in file [ROOT]/phpbb/class_loader.php on line 160: require(./../ext/boardtools/quickreply/event/listener_helper.php): failed to open stream: No such file or directory

Fatal error: require(): Failed opening required './../ext/boardtools/quickreply/event/listener_helper.php' (include_path='.:/opt/cpanel/ea-php56/root/usr/share/pear') in

**Comment by Tatiana5** [comment]
@ricardorohde 
Download `ext/boardtools/quickreply/event/listener_helper.php` file to the server
