### ISSUE TITLE
Integration with ABBC broken after upgrade to ABBC 3.2.1

### ISSUE THREAD

**Issue by obagley** [Tatiana5/QuickReply#82]
Following upgrade from ABBC 3.2.0 to 3.2.1, the integration with QuickReply is broken, see picture

![broken quick reply](https://user-images.githubusercontent.com/40397642/43368872-9e5e462a-935b-11e8-9827-5bc217410660.JPG)

Tried so far:
1. Enabling and Disabling both extensions (QR and ABBC) in different order, with and without deleting data.
2. Removing ABBC completely, removing manually all codes installed by ABBC, then installing ABBC from scratch.

As long as ABBC is not enabled - everything is fine in QR. The moment it is enabled, QR shows icons from ABBC messed up as in the picture below, but without second line ("format-buttons" in the code). Disabling and re-enabling ABBC results in both lines of buttons shown - from ABBC and format-buttons.

For now going back to the previous setup with ABBC 3.2.0

**Comment by Tatiana5** [comment]
Fixed https://github.com/BoardTools/QuickReply/commit/3caee0cba245f945c096b190cefe8b8494db1572

(Duplication of buttons is not because of ABBC3)
