### ISSUE TITLE
Incorrect the username of quoted text in mobile Chrome on Android

### ISSUE THREAD

**Issue by Meliorik** [Tatiana5/QuickReply#88]
phpbb: 3.2.2... no final ((
QuickReply Reloaded: 2.0.0-beta4

After the upgrade expansion, there was a problem that the quoted text is assigned to the authorship of the user of the first message on the page.

This problem is in the mobile Chrome on Android... maybe in other mobile browsers.

![Screenshot_20191125-1222323102](https://user-images.githubusercontent.com/10316114/69529628-b4fe8b80-0f81-11ea-94ba-05a71478f9a0.jpg)

**Comment by micronull** [comment]
Подтверждаю. Пользователи жалуются на такую же проблему, в частности на iOS. 
--
I confirm. Users complain about the same problem, in particular on iOS.

Last @dev vesion, commit from 8 okt.

**Comment by Galixte** [comment]
Hi @lavigor @Tatiana5,

could you take a look, please?

**Comment by Galixte** [comment]
Bump @rxu @lavigor  @Tatiana5 Could you take a look, please?

Regards.

**Comment by Tatiana5** [comment]
https://github.com/BoardTools/QuickReply/tree/2.1.x
