### ISSUE TITLE
phpBB 3.3

### ISSUE THREAD

**Issue by Aurelienazerty** [Tatiana5/QuickReply#89]
The 2.0 beta 4 is not phpBB 3.3 compatible.

**Comment by lavigor** [comment]
Yes, we know that, thank you.
As soon as we have more time, we'll do the fixes.
As for me, I'll have more time at around February.

Sorry for inconvenience and a late release.

**Comment by Aurelienazerty** [comment]
Did you found time for phpBB 3.3 compatibility ?

**Comment by webliberty** [comment]
Any news about compatibility with phpBB 3.3?
What year are you talking about the month of February?

**Comment by Tatiana5** [comment]
https://github.com/BoardTools/QuickReply/tree/2.1.x
