### ISSUE TITLE
ABBC3 and QuickReply on 3.3.2 not work fine

### ISSUE THREAD

**Issue by TheRealMrDrap** [Tatiana5/QuickReply#92]
I show this on my FRESH installation:
![image](https://user-images.githubusercontent.com/15906850/102547644-c9945100-40b9-11eb-9574-d5b644294906.png)

If you go to the bottom:
![image](https://user-images.githubusercontent.com/15906850/102547561-aa95bf00-40b9-11eb-88d8-f3d2d97f94c0.png)

**Comment by Tatiana5** [comment]
QuickReply **2.1.0-alpha** + ABBC3 **3.3.0** + https://www.phpbbguru.net/community/viewtopic.php?p=548180#p548180

**Comment by TheRealMrDrap** [comment]
This 'idea' don't make works fine ABBC3
Now I see allways this:
![image](https://user-images.githubusercontent.com/15906850/102657342-cbbbe580-4175-11eb-84a0-3fafa42614b2.png)

But When I desactivate QuickReply I see this on reply:
![image](https://user-images.githubusercontent.com/15906850/102657496-0faeea80-4176-11eb-9a91-d55aaf6b7ebf.png)

On ABBC3 I put custom Icons for my personal bbcode, and selected the png code:
![image](https://user-images.githubusercontent.com/15906850/102657644-500e6880-4176-11eb-9979-76ad8368d58c.png)
----

**Comment by Tatiana5** [comment]
It is not idea, it is solution
Complete all 3 conditions and clear the forum and browser cache

And check the QuickReply Reloaded and ABBC3 settings so that buttons in quick reply are included everywhere

**Comment by TheRealMrDrap** [comment]
_'clear the forum and browser cache'_ 
WAS THE SOLUTION!!! so glad for the help!
