### ISSUE TITLE
Error when creating sub forum

### ISSUE THREAD

**Issue by Aurelienazerty** [Tatiana5/QuickReply#93]
Hi,

when I create a sub forum, I have this error : 

`Got error 'PHP message: PHP Fatal error:  Uncaught Twig\\Error\\SyntaxError: Unexpected token "name" of value "S_ENABLE_QR_AJAX_SUBMIT" ("end of statement block" expected). in /var/www/team-azerty.com/www/forum/ext/boardtools/quickreply/adm/style/event/acp_forums_normal_settings_append.html:4\nStack trace:\n#0 /var/www/team-azerty.com/www/forum/vendor/twig/twig/src/TokenParser/IfTokenParser.php(38): Twig\\TokenStream->expect(3)\n#1 /var/www/team-azerty.com/www/forum/vendor/twig/twig/src/Parser.php(185): Twig\\TokenParser\\IfTokenParser->parse(Object(Twig\\Token))\n#2 /var/www/team-azerty.com/www/forum/vendor/twig/twig/src/TokenParser/IfTokenParser.php(39): Twig\\Parser->subparse(Array)\n#3 /var/www/team-azerty.com/www/forum/vendor/twig/twig/src/Parser.php(185): Twig\\TokenParser\\IfTokenParser->parse(Object(Twig\\Token))\n#4 /var/www/team-azerty.com/www/forum/vendor/twig/twig/src/Parser.php(98): Twig\\Parser->subparse(NULL, false)\n#5 /var/www/team-azerty.com/www/forum/vendor/twig/twig/src/Environment.php(563): Twig\\Parser->p...', referer: https://www.team-azerty.com/forum/adm/index.php?i=acp_forums&sid=0ce7fe6f7b962c6360c42c116db2e01e&icat=269&mode=manage&parent_id=5`

**Comment by Tatiana5** [comment]
https://github.com/BoardTools/QuickReply/blob/2.1.x/adm/style/event/acp_forums_normal_settings_append.html - there is no errors
Update the extension
