### ISSUE TITLE
 Wrong last post anchor position on scroll	

### ISSUE THREAD

**Issue by elchio** [Tatiana5/QuickReply#94]
[Repost ](https://www.phpbb.com/customise/db/extension/quickreply/support/topic/227396) from phpbb.com forum ;)

For example - when I click notification and website scroll to last post it is positioned incorectly, usually at the very bottom.

I figured out that it could be connected with generating qr_form_placeholder when this small fixed editor is shown.

I'll be really glad if you could you check this :)

BTW
Same thing happens on your demo page (https://boardtools.ru/QuickReply) with a little help of browser developer tools ;) - so I assume it could be some problem with code.

**Comment by Tatiana5** [comment]
Fixed

**Comment by elchio** [comment]
Oh :)

Thx - i am going to test it right away :D

EDIT:
So there another problem connected. If I'm on main site and click notification ti goes to last post anchor now - so it is ok. But if i click one more time the same notification - website scrolls to message posting area, not to last post.

Could you check?

**Comment by elchio** [comment]
So there another problem connected. If I'm on main site and click notification ti goes to last post anchor now - so it is ok. But if i click one more time the same notification - website scrolls to message posting area, not to last post.

Could you check?
